apiVersion: v1
kind: ServiceAccount
metadata:
  name: card
  namespace: card

  labels:
    app.kubernetes.io/name: card
    app.kubernetes.io/part-of: hsbc
    environment: prod

automountServiceAccountToken: false
