apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: account-db-secret
  namespace: account

  labels:
    app.kubernetes.io/name: account
    app.kubernetes.io/part-of: hsbc
    environment: prod

spec:
  provider: aws

  parameters:
    region: ap-south-1

    objects: |
      - objectName: "hsbc-prod-account-db"
        objectType: "secretsmanager"

        jmesPath:
          - path: username
            objectAlias: username

          - path: password
            objectAlias: password

  secretObjects:
    - secretName: account-db-secret
      type: Opaque

      data:
        - objectName: username
          key: username

        - objectName: password
          key: password
