apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
  namespace: account

  labels:
    app.kubernetes.io/name: account
    app.kubernetes.io/part-of: hsbc
    environment: prod

automountServiceAccountToken: false
