apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: account

  labels:
    app: account
    app.kubernetes.io/name: account
    app.kubernetes.io/part-of: hsbc
    environment: prod

spec:
  type: ClusterIP

  selector:
    app: account

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
