apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend

  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: hsbc
    environment: prod

data:
  API_BASE_PATH: "/api"

  CUSTOMER_API_PATH: "/api/customer"
  ACCOUNT_API_PATH: "/api/account"
  CARD_API_PATH: "/api/card"
