# API version provided by the Secrets Store CSI Driver
apiVersion: secrets-store.csi.x-k8s.io/v1

# Creates a SecretProviderClass
kind: SecretProviderClass

metadata:
  # Name of this SecretProviderClass
  # This name is referenced by deployment.yaml
  name: customer-db-secret

  # Namespace where the SecretProviderClass is created
  namespace: customer

  labels:
    app.kubernetes.io/name: customer
    app.kubernetes.io/part-of: hsbc
    environment: prod

spec:

  # AWS provider is used to retrieve secrets from AWS Secrets Manager
  provider: aws

  parameters:

    # AWS region where the secret is stored
    region: ap-south-1

    # Defines which AWS Secrets Manager secret to retrieve
    objects: |

      # Name of the secret in AWS Secrets Manager
      - objectName: "hsbc-prod-customer-db"

        # Tells the AWS provider that the object is from Secrets Manager
        objectType: "secretsmanager"

        # Extract individual values from the JSON secret
        jmesPath:

          # Read the username field from the AWS secret
          # Store it with the alias "username"
          - path: username
            objectAlias: username

          # Read the password field from the AWS secret
          # Store it with the alias "password"
          - path: password
            objectAlias: password

  # Creates/synchronizes a Kubernetes Secret from the retrieved values
  secretObjects:

    # Name of the Kubernetes Secret that will be created
    - secretName: customer-db-secret

      # Opaque means it contains arbitrary key-value data
      type: Opaque

      data:

        # Take the retrieved "username" value
        # and store it as the "username" key
        - objectName: username
          key: username

        # Take the retrieved "password" value
        # and store it as the "password" key
        - objectName: password
          key: password
