# Kubernetes API version used for ServiceAccount
apiVersion: v1

# Creates a ServiceAccount
kind: ServiceAccount

metadata:
  # Name of the ServiceAccount
  # This name is referenced in deployment.yaml
  name: customer

  # Namespace where the ServiceAccount is created
  namespace: customer

  labels:
    app.kubernetes.io/name: customer
    app.kubernetes.io/part-of: hsbc
    environment: prod

# Prevent automatically mounting the Kubernetes API token into the Pod
# The application does not need the Kubernetes API token
automountServiceAccountToken: false
